name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Navigate to SampleJunitTest and Verify
      run: |
        cd SampleJunitTest
        ls -al
      shell: bash

    - name: Build and Test with Maven
      working-directory: SampleJunitTest
      run: mvn test

